In [1]:
import requests
from io import BytesIO
from PyPDF2 import PdfReader
import pandas as pd

In [5]:
# Section 1: AI-Related Research Keywords
ai_keywords = [
    "Artificial Intelligence",
    "Machine Learning",
    "Deep Learning",
    "Neural Networks",
    "Reinforcement Learning",
    "Natural Language Processing",
    "Computer Vision",
    "Data Mining",
    "Pattern Recognition",
    "AI Ethics",
    "Explainable AI",
    "Generative Adversarial Networks",
    "Convolutional Neural Networks",
    "Recurrent Neural Networks",
    "Transfer Learning",
    "Bayesian Networks",
    "Evolutionary Algorithms",
    "Swarm Intelligence",
    "Fuzzy Logic Systems",
    "Decision Trees",
    "Support Vector Machines",
    "Clustering Algorithms",
    "Semi-Supervised Learning",
    "Unsupervised Learning",
    "Supervised Learning",
    "Regression Analysis",
    "Random Forest",
    "Gradient Boosting",
    "Ensemble Learning",
    "Dimensionality Reduction",
    "Autoencoders",
    "Data Augmentation",
    "Cognitive Computing",
    "Robotics and AI",
    "Autonomous Systems",
    "Human-Robot Interaction",
    "Multi-Agent Systems",
    "Semantic Segmentation",
    "Object Detection",
    "Visual Question Answering",
    "Speech Recognition",
    "Natural Language Understanding",
    "Sentiment Analysis",
    "Text Mining",
    "Knowledge Graphs",
    "Graph Neural Networks",
    "AI in Healthcare",
    "AI in Education",
    "AI in Finance",
    "AI in Cybersecurity",
    "AI and Big Data",
    "AI for Social Good",
    "Reinforcement Learning in Games",
    "Policy Gradient Methods",
    "Imitation Learning",
    "Model-Based Reinforcement Learning",
    "Meta-Learning",
    "Few-Shot Learning",
    "Zero-Shot Learning",
    "Adversarial Machine Learning",
    "Robustness in AI",
    "Federated Learning",
    "Edge AI",
    "IoT and AI",
    "AI for Smart Cities",
    "Natural Language Generation",
    "Machine Translation",
    "Speech Synthesis",
    "Human-Centered AI",
    "AI and Privacy",
    "Data Privacy in AI",
    "Differential Privacy in Machine Learning",
    "Computational Intelligence",
    "Hybrid AI Systems",
    "AI for Decision Support",
    "Predictive Analytics in AI",
    "Optimization in AI",
    "Self-Supervised Learning",
    "Semi-Autonomous Systems",
    "Evolutionary Computation",
    "Genetic Algorithms",
    "Neuroevolution",
    "Fraud Detection in AI",
    "Digital Twins in AI",
    "Path Planning in Robotics",
    "Autonomous Driving",
    "Deep Reinforcement Learning",
    "AI for Environmental Monitoring",
    "AI in Agriculture",
    "AI in Manufacturing",
    "Interpretable Machine Learning",
    "Neural Network Interpretability",
    "AI in Marketing",
    "AI in Supply Chain Management",
    "Quantum Machine Learning",
    "AI Benchmarking",
    "Multi-Task Learning",
    "Computational Neuroscience and AI",
    "AI for Personalized Medicine"
]

# Section 2: Additional Deep Learning Keywords
deep_learning_keywords = [
    "Convolutional Neural Networks (CNN)",
    "CNN",
    "Recurrent Neural Networks (RNN)",
    "RNN",
    "Long Short-Term Memory (LSTM)",
    "LSTM",
    "Gated Recurrent Unit (GRU)",
    "GRU",
    "Autoencoder",
    "Variational Autoencoder (VAE)",
    "VAE",
    "Generative Adversarial Networks (GAN)",
    "GAN",
    "Deep Reinforcement Learning",
    "Residual Networks (ResNet)",
    "ResNet",
    "DenseNet",
    "Capsule Networks",
    "Transformer Networks",
    "Attention Mechanism",
    "Bidirectional Encoder Representations from Transformers (BERT)",
    "BERT",
    "Generative Pre-trained Transformer (GPT)",
    "GPT",
    "XLNet",
    "RoBERTa",
    "EfficientNet",
    "YOLO (You Only Look Once)",
    "YOLO",
    "Faster R-CNN",
    "Mask R-CNN",
    "U-Net",
    "SegNet",
    "Deep Belief Networks (DBN)",
    "DBN",
    "Restricted Boltzmann Machine (RBM)",
    "RBM",
    "Self-Supervised Learning",
    "Unsupervised Representation Learning",
    "Neural Architecture Search",
    "Hyperparameter Optimization in Deep Learning",
    "Transfer Learning in Deep Learning",
    "Domain Adaptation in Deep Learning",
    "Fine-Tuning Neural Networks",
    "Multi-Modal Deep Learning",
    "Graph Convolutional Networks (GCN)",
    "GCN",
    "Recurrent Convolutional Neural Networks",
    "Attention-based Convolutional Neural Networks",
    "Deep Q-Network (DQN)",
    "DQN",
    "Policy Gradient Methods in Deep RL",
    "Actor-Critic Methods",
    "Sequence-to-Sequence Models",
    "End-to-End Deep Learning",
    "Deep Feature Extraction",
    "Model Compression in Deep Learning",
    "Neural Network Pruning",
    "Quantization in Neural Networks",
    "Federated Deep Learning",
    "Self-Attention Networks",
    "Neural Style Transfer",
    "Data Augmentation for Deep Learning",
    "Deep Metric Learning"
]

# Section 3: Machine Learning Keywords
machine_learning_keywords = [
    "Machine Learning",
    "Supervised Learning",
    "Unsupervised Learning",
    "Semi-Supervised Learning",
    "Reinforcement Learning",
    "Decision Trees",
    "Random Forest",
    "Support Vector Machines",
    "Logistic Regression",
    "Linear Regression",
    "Naive Bayes",
    "K-Nearest Neighbors",
    "Clustering",
    "K-Means Clustering",
    "Hierarchical Clustering",
    "DBSCAN",
    "Principal Component Analysis (PCA)",
    "PCA",
    "Singular Value Decomposition (SVD)",
    "SVD",
    "Dimensionality Reduction",
    "Ensemble Learning",
    "Boosting",
    "Bagging",
    "Gradient Boosting",
    "AdaBoost",
    "XGBoost",
    "LightGBM",
    "CatBoost",
    "Bayesian Networks",
    "Probabilistic Graphical Models",
    "Hidden Markov Model (HMM)",
    "HMM",
    "Kernel Methods",
    "Kernel PCA",
    "Regression Analysis",
    "Classification Algorithms",
    "Neural Networks",
    "Learning Algorithms",
    "Model Evaluation",
    "Cross-Validation",
    "Hyperparameter Tuning",
    "Grid Search",
    "Random Search",
    "Model Selection",
    "Feature Engineering",
    "Data Preprocessing",
    "Distributed Learning",
    "Online Learning",
    "Meta Learning",
    "Feature Selection",
    "Anomaly Detection",
    "Machine Learning Applications"
]

In [6]:
from serpapi import GoogleSearch

def search_google_scholar(query):
    # SERP API 엔드포인트와 필요한 파라미터 구성
    params = {
    "engine": "google_scholar",
    "q": query,
    "api_key": "YOUR_API_KEY",
    "num" : 20,
    "hi" : "en",
    "as_ylo" : "2019"
    }
    
    # GET 요청 보내기
    search = GoogleSearch(params)
    # HTTP 오류 발생 시 예외 처리
    results = search.get_dict()
    print(results)
    organic_results = results["organic_results"]
    #print(type(organic_results))
    # JSON 결과 반환
    return organic_results

In [171]:
query = 'deep+learning'
organic_results = search_google_scholar(query)

<class 'list'>

In [2]:
df = pd.read_csv('papers_link2.csv')
df

,title,snippet,link
0,Applications for deep learning in ecology,"… However, to our knowledge, we currently lack...",https://besjournals.onlinelibrary.wiley.com/do...
1,Machine learning and deep learning,… Machine learning describes the capacity of s...,https://link.springer.com/content/pdf/10.1007/...
2,Fundamentals of deep learning,"… , computer vision, and reinforcement learnin...",https://coursesteach.com/pluginfile.php/7459/m...
3,Deep learning for AI,… We reviewed the basic concepts and some of t...,https://dl.acm.org/doi/pdf/10.1145/3448250
4,The computational limits of deep learning,… deep learning is so computationally expensiv...,https://assets.pubpub.org/9c76pmmn/11686018723...
...,...,...,...
2282,Revolutionizing healthcare: the role of artifi...,… The advent of high-throughput genomic sequen...,https://link.springer.com/content/pdf/10.1186/...
2283,AI-based smart prediction of clinical disease ...,"… Thus, these data are only utilized for analy...",https://link.springer.com/content/pdf/10.1007/...
2284,Challenges in establishing pure lung cancer or...,… Clinical implementation of tumor organoids f...,https://www.cell.com/cell-reports/pdfExtended/...
2285,“Bridging the Gap” Everything that Could Have ...,… Gender medicine is the first step of persona...,https://www.mdpi.com/1422-0067/21/1/296/pdf
2286,"Artificial intelligence (AI) in medicine, curr...",… AI promises to revolutionize patient care in...,https://link.springer.com/content/pdf/10.1186/...

In [232]:
for query in ai_keywords:
    organic_results = search_google_scholar(query)
    #print(organic_results)
    df = extract_paper_info(organic_results, df)

{'search_metadata': {'id': '67a89843fc86e9ade6cd6207', 'status': 'Success', 'json_endpoint': 'https://serpapi.com/searches/117b3c7b7cfd6225/67a89843fc86e9ade6cd6207.json', 'created_at': '2025-02-09 11:57:55 UTC', 'processed_at': '2025-02-09 11:57:55 UTC', 'google_scholar_url': 'https://scholar.google.com/scholar?q=Artificial+Intelligence&hl=en&num=21&as_ylo=2019', 'raw_html_file': 'https://serpapi.com/searches/117b3c7b7cfd6225/67a89843fc86e9ade6cd6207.html', 'total_time_taken': 1.08}, 'search_parameters': {'engine': 'google_scholar', 'q': 'Artificial Intelligence', 'hl': 'en', 'num': '20', 'as_ylo': '2019'}, 'search_information': {'organic_results_state': 'Results for exact spelling', 'total_results': 38900, 'time_taken_displayed': 0.11, 'query_displayed': 'Artificial Intelligence'}, 'organic_results': [{'position': 1, 'title': 'Causability and explainability of artificial intelligence in medicine', 'result_id': 'aTI2DQaQV8gJ', 'link': 'https://wires.onlinelibrary.wiley.com/doi/abs/10.1002/widm.1312', 'snippet': 'Explainable artificial intelligence (AI) is attracting much interest in medicine. Technically, the problem of explainability is as old as AI itself and classic AI represented comprehensible …', 'publication_info': {'summary': 'A Holzinger, G Langs, H Denk… - … Reviews: Data Mining …, 2019 - Wiley Online Library', 'authors': [{'name': 'A Holzinger', 'link': 'https://scholar.google.com/citations?user=BTBd5V4AAAAJ&hl=en&num=20&oi=sra', 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=BTBd5V4AAAAJ&engine=google_scholar_author&hl=en', 'author_id': 'BTBd5V4AAAAJ'}, {'name': 'G Langs', 'link': 'https://scholar.google.com/citations?user=wmNUtZEAAAAJ&hl=en&num=20&oi=sra', 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=wmNUtZEAAAAJ&engine=google_scholar_author&hl=en', 'author_id': 'wmNUtZEAAAAJ'}]}, 'resources': [{'title': 'wiley.com', 'file_format': 'PDF', 'link': 'https://wires.onlinelibrary.wiley.com/doi/pdf/10.1002/widm.1312'}], 'inline_links': {'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&hl=en&q=aTI2DQaQV8gJ', 'cited_by': {'total': 1603, 'link': 'https://scholar.google.com/scholar?cites=14436165486225273449&as_sdt=80005&sciodt=0,11&hl=en&num=20', 'cites_id': '14436165486225273449', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=80005&cites=14436165486225273449&engine=google_scholar&hl=en&num=20'}, 'related_pages_link': 'https://scholar.google.com/scholar?q=related:aTI2DQaQV8gJ:scholar.google.com/&scioq=Artificial+Intelligence&hl=en&num=20&as_sdt=0,11&as_ylo=2019', 'serpapi_related_pages_link': 'https://serpapi.com/search.json?as_sdt=0%2C11&as_ylo=2019&engine=google_scholar&hl=en&num=20&q=related%3AaTI2DQaQV8gJ%3Ascholar.google.com%2F', 'versions': {'total': 9, 'link': 'https://scholar.google.com/scholar?cluster=14436165486225273449&hl=en&num=20&as_sdt=0,11&as_ylo=2019', 'cluster_id': '14436165486225273449', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C11&as_ylo=2019&cluster=14436165486225273449&engine=google_scholar&hl=en&num=20'}}}, {'position': 2, 'title': 'Introduction to artificial intelligence', 'result_id': '3KMijQ7-ItsJ', 'type': 'Book', 'link': 'https://books.google.com/books?hl=en&lr=&id=O7kfEQAAQBAJ&oi=fnd&pg=PR5&dq=Artificial+Intelligence&ots=JnzLHAzof1&sig=wvpCb_xT8CahDd1ciF8xEEHjOZk', 'snippet': '… during your studies this book will help you share my fascination with Artificial Intelligence. … philosophical questions surrounding intelligence and artificial intelligence. We humans have …', 'publication_info': {'summary': 'W Ertel - 2024 - books.google.com', 'authors': [{'name': 'W Ertel', 'link': 'https://scholar.google.com/citations?user=Zplrd3EAAAAJ&hl=en&num=20&oi=sra', 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=Zplrd3EAAAAJ&engine=google_scholar_author&hl=en', 'author_id': 'Zplrd3EAAAAJ'}]}, 'resources': [{'title': 'hoasen.edu.vn', 'file_format': 'PDF', 'link': 'https://thuvienso.hoasen.edu.vn/bitstream/handle/123456789/10507/Contents.pdf?sequence=1&isAllowed=y'}], 'inline_links': {'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&hl=en&q=3KMijQ7-ItsJ', 'cited_by': {'total': 1045, 'link': 'https://scholar.google.com/scholar?cites=15790462581965235164&as_sdt=80005&sciodt=0,11&hl=en&num=20', 'cites_id': '15790462581965235164', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=80005&cites=15790462581965235164&engine=google_scholar&hl=en&num=20'}, 'related_pages_link': 'https://scholar.google.com/scholar?q=related:3KMijQ7-ItsJ:scholar.google.com/&scioq=Artificial+Intelligence&hl=en&num=20&as_sdt=0,11&as_ylo=2019', 'serpapi_related_pages_link': 'https://serpapi.com/search.json?as_sdt=0%2C11&as_ylo=2019&engine=google_scholar&hl=en&num=20&q=related%3A3KMijQ7-ItsJ%3Ascholar.google.com%2F', 'versions': {'total': 19, 'link': 'https://scholar.google.com/scholar?cluster=15790462581965235164&hl=en&num=20&as_sdt=0,11&as_ylo=2019', 'cluster_id': '15790462581965235164', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C11&as_ylo=2019&cluster=15790462581965235164&engine=google_scholar&hl=en&num=20'}}}, {'position': 3, 'title': 'Introduction to artificial intelligence in medicine', 'result_id': 't7R4cXLBtzQJ', 'link': 'https://www.tandfonline.com/doi/abs/10.1080/13645706.2019.1575882', 'snippet': 'The term Artificial Intelligence (AI) was coined by John McCarthy in 1956 during a conference held on this subject. However, the possibility of machines being able to simulate human …', 'publication_info': {'summary': 'Y Mintz, R Brodie - Minimally Invasive Therapy & Allied …, 2019 - Taylor & Francis', 'authors': [{'name': 'Y Mintz', 'link': 'https://scholar.google.com/citations?user=LP924c8AAAAJ&hl=en&num=20&oi=sra', 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=LP924c8AAAAJ&engine=google_scholar_author&hl=en', 'author_id': 'LP924c8AAAAJ'}]}, 'inline_links': {'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&hl=en&q=t7R4cXLBtzQJ', 'cited_by': {'total': 854, 'link': 'https://scholar.google.com/scholar?cites=3798717507984471223&as_sdt=80005&sciodt=0,11&hl=en&num=20', 'cites_id': '3798717507984471223', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=80005&cites=3798717507984471223&engine=google_scholar&hl=en&num=20'}, 'related_pages_link': 'https://scholar.google.com/scholar?q=related:t7R4cXLBtzQJ:scholar.google.com/&scioq=Artificial+Intelligence&hl=en&num=20&as_sdt=0,11&as_ylo=2019', 'serpapi_related_pages_link': 'https://serpapi.com/search.json?as_sdt=0%2C11&as_ylo=2019&engine=google_scholar&hl=en&num=20&q=related%3At7R4cXLBtzQJ%3Ascholar.google.com%2F', 'versions': {'total': 3, 'link': 'https://scholar.google.com/scholar?cluster=3798717507984471223&hl=en&num=20&as_sdt=0,11&as_ylo=2019', 'cluster_id': '3798717507984471223', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C11&as_ylo=2019&cluster=3798717507984471223&engine=google_scholar&hl=en&num=20'}}}, {'position': 4, 'title': 'History of artificial intelligence in medicine', 'result_id': 'f-Qp_A_K_I0J', 'link': 'https://www.sciencedirect.com/science/article/pii/S0016510720344667', 'snippet': '… were capable of human intelligence. Six years later, John McCarthy described the term artificial intelligence (AI) as “the science and engineering of making intelligent machines.” …', 'publication_info': {'summary': 'V Kaul, S Enslin, SA Gross - Gastrointestinal endoscopy, 2020 - Elsevier'}, 'resources': [{'title': 'giejournal.org', 'file_format': 'HTML', 'link': 'https://www.giejournal.org/article/S0016-5107(20)34466-7/fulltext'}], 'inline_links': {'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&hl=en&q=f-Qp_A_K_I0J', 'html_version': 'https://www.giejournal.org/article/S0016-5107(20)34466-7/fulltext', 'cited_by': {'total': 959, 'link': 'https://scholar.google.com/scholar?cites=10231274623482848383&as_sdt=80005&sciodt=0,11&hl=en&num=20', 'cites_id': '10231274623482848383', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=80005&cites=10231274623482848383&engine=google_scholar&hl=en&num=20'}, 'related_pages_link': 'https://scholar.google.com/scholar?q=related:f-Qp_A_K_I0J:scholar.google.com/&scioq=Artificial+Intelligence&hl=en&num=20&as_sdt=0,11&as_ylo=2019', 'serpapi_related_pages_link': 'https://serpapi.com/search.json?as_sdt=0%2C11&as_ylo=2019&engine=google_scholar&hl=en&num=20&q=related%3Af-Qp_A_K_I0J%3Ascholar.google.com%2F', 'versions': {'total': 5, 'link': 'https://scholar.google.com/scholar?cluster=10231274623482848383&hl=en&num=20&as_sdt=0,11&as_ylo=2019', 'cluster_id': '10231274623482848383', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C11&as_ylo=2019&cluster=10231274623482848383&engine=google_scholar&hl=en&num=20'}}}, {'position': 5, 'title': 'Introduction to artificial intelligence', 'result_id': 'PDdoPXU3gCEJ', 'type': 'Book', 'link': 'https://books.google.com/books?hl=en&lr=&id=vC-oDwAAQBAJ&oi=fnd&pg=PA33&dq=Artificial+Intelligence&ots=XMX8ZJJCCo&sig=q2DQbaW6oBFY14va8Lw3hjT0u9A', 'snippet': '… intelligent enough to understand intelligence? One approach to answering this question is “artificial intelligence… Much progress has been made in research on artificial intelligence since …', 'publication_info': {'summary': 'PC Jackson - 2019 - books.google.com', 'authors': [{'name': 'PC Jackson', 'link': 'https://scholar.google.com/citations?user=numVGwQAAAAJ&hl=en&num=20&oi=sra', 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=numVGwQAAAAJ&engine=google_scholar_author&hl=en', 'author_id': 'numVGwQAAAAJ'}]}, 'resources': [{'title': 'everand.com', 'file_format': 'HTML', 'link': 'https://www.everand.com/book/271648175/Introduction-to-Artificial-Intelligence-Second-Enlarged-Edition'}], 'inline_links': {'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&hl=en&q=PDdoPXU3gCEJ', 'html_version': 'https://www.everand.com/book/271648175/Introduction-to-Artificial-Intelligence-Second-Enlarged-Edition', 'cited_by': {'total': 514, 'link': 'https://scholar.google.com/scholar?cites=2413990376951527228&as_sdt=80005&sciodt=0,11&hl=en&num=20', 'cites_id': '2413990376951527228', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=80005&cites=2413990376951527228&engine=google_scholar&hl=en&num=20'}, 'related_pages_link': 'https://scholar.google.com/scholar?q=related:PDdoPXU3gCEJ:scholar.google.com/&scioq=Artificial+Intelligence&hl=en&num=20&as_sdt=0,11&as_ylo=2019', 'serpapi_related_pages_link': 'https://serpapi.com/search.json?as_sdt=0%2C11&as_ylo=2019&engine=google_scholar&hl=en&num=20&q=related%3APDdoPXU3gCEJ%3Ascholar.google.com%2F', 'versions': {'total': 6, 'link': 'https://scholar.google.com/scholar?cluster=2413990376951527228&hl=en&num=20&as_sdt=0,11&as_ylo=2019', 'cluster_id': '2413990376951527228', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C11&as_ylo=2019&cluster=2413990376951527228&engine=google_scholar&hl=en&num=20'}}}, {'position': 6, 'title': 'Artificial intelligence and medicine', 'result_id': 'FdO_0DaUwkQJ', 'link': 'https://www.taylorfrancis.com/chapters/edit/10.4324/9780429052071-1/artificial-intelligence-medicine-peter-szolovits', 'snippet': '… This book is ~n introduction to the field of Artificial Intelligence in Medicine, (abbreviated AIM… some of the fundamental ideas of artificial intelligence, briefly describes the current state of …', 'publication_info': {'summary': 'P Szolovits - Artificial intelligence in medicine, 2019 - taylorfrancis.com', 'authors': [{'name': 'P Szolovits', 'link': 'https://scholar.google.com/citations?user=1LuGqFQAAAAJ&hl=en&num=20&oi=sra', 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=1LuGqFQAAAAJ&engine=google_scholar_author&hl=en', 'author_id': '1LuGqFQAAAAJ'}]}, 'resources': [{'title': 'mit.edu', 'file_format': 'HTML', 'link': 'https://groups.csail.mit.edu/medg/ftp/psz/AIM82/ch1.html'}], 'inline_links': {'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&hl=en&q=FdO_0DaUwkQJ', 'html_version': 'https://groups.csail.mit.edu/medg/ftp/psz/AIM82/ch1.html', 'cited_by': {'total': 465, 'link': 'https://scholar.google.com/scholar?cites=4954685503212344085&as_sdt=80005&sciodt=0,11&hl=en&num=20', 'cites_id': '4954685503212344085', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=80005&cites=4954685503212344085&engine=google_scholar&hl=en&num=20'}, 'related_pages_link': 'https://scholar.google.com/scholar?q=related:FdO_0DaUwkQJ:scholar.google.com/&scioq=Artificial+Intelligence&hl=en&num=20&as_sdt=0,11&as_ylo=2019', 'serpapi_related_pages_link': 'https://serpapi.com/search.json?as_sdt=0%2C11&as_ylo=2019&engine=google_scholar&hl=en&num=20&q=related%3AFdO_0DaUwkQJ%3Ascholar.google.com%2F', 'versions': {'total': 8, 'link': 'https://scholar.google.com/scholar?cluster=4954685503212344085&hl=en&num=20&as_sdt=0,11&as_ylo=2019', 'cluster_id': '4954685503212344085', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C11&as_ylo=2019&cluster=4954685503212344085&engine=google_scholar&hl=en&num=20'}, 'cached_page_link': 'https://scholar.googleusercontent.com/scholar?q=cache:FdO_0DaUwkQJ:scholar.google.com/+Artificial+Intelligence&hl=en&num=20&as_sdt=0,11&as_ylo=2019'}}, {'position': 7, 'title': 'Overview of artificial intelligence in medicine', 'result_id': '4hI-d2vssaYJ', 'link': 'https://journals.lww.com/jfmpc/fulltext/2019/08070/Overview_of_artificial_intelligence_in_medicine.27.aspx', 'snippet': '… on the fact that the intelligent behavior of a computer is … Artificial intelligent techniques such as fuzzy expert systems, Bayesian networks, artificial neural networks, and hybrid intelligent …', 'publication_info': {'summary': 'P Malik, M Pathania, VK Rathaur - Journal of family medicine …, 2019 - journals.lww.com', 'authors': [{'name': 'P Malik', 'link': 'https://scholar.google.com/citations?user=SWugjlwAAAAJ&hl=en&num=20&oi=sra', 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=SWugjlwAAAAJ&engine=google_scholar_author&hl=en', 'author_id': 'SWugjlwAAAAJ'}, {'name': 'VK Rathaur', 'link': 'https://scholar.google.com/citations?user=mbF9-TMAAAAJ&hl=en&num=20&oi=sra', 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=mbF9-TMAAAAJ&engine=google_scholar_author&hl=en', 'author_id': 'mbF9-TMAAAAJ'}]}, 'resources': [{'title': 'lww.com', 'file_format': 'PDF', 'link': 'https://journals.lww.com/jfmpc/_layouts/15/oaks.journals/downloadpdf.aspx?an=01697686-201908070-00027'}], 'inline_links': {'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&hl=en&q=4hI-d2vssaYJ', 'cited_by': {'total': 1129, 'link': 'https://scholar.google.com/scholar?cites=12011641627480036066&as_sdt=80005&sciodt=0,11&hl=en&num=20', 'cites_id': '12011641627480036066', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=80005&cites=12011641627480036066&engine=google_scholar&hl=en&num=20'}, 'related_pages_link': 'https://scholar.google.com/scholar?q=related:4hI-d2vssaYJ:scholar.google.com/&scioq=Artificial+Intelligence&hl=en&num=20&as_sdt=0,11&as_ylo=2019', 'serpapi_related_pages_link': 'https://serpapi.com/search.json?as_sdt=0%2C11&as_ylo=2019&engine=google_scholar&hl=en&num=20&q=related%3A4hI-d2vssaYJ%3Ascholar.google.com%2F', 'versions': {'total': 9, 'link': 'https://scholar.google.com/scholar?cluster=12011641627480036066&hl=en&num=20&as_sdt=0,11&as_ylo=2019', 'cluster_id': '12011641627480036066', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C11&as_ylo=2019&cluster=12011641627480036066&engine=google_scholar&hl=en&num=20'}}}, {'position': 8, 'title': 'Managing artificial intelligence.', 'result_id': '75ZX7-22gRkJ', 'type': 'Pdf', 'link': 'https://www.academia.edu/download/75230000/Berente_Gu_Recker_Santhanam_2021_MISQ.pdf', 'snippet': '… that actually achieved intelligent behavior, … artificial intelligence for having borne and nurtured it. If you could see how it was done, people seemed to think, then it couldn’t be intelligence…', 'publication_info': {'summary': 'N Berente, B Gu, J Recker, R Santhanam - MIS quarterly, 2021 - academia.edu', 'authors': [{'name': 'N Berente', 'link': 'https://scholar.google.com/citations?user=xKzbu4QAAAAJ&hl=en&num=20&oi=sra', 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=xKzbu4QAAAAJ&engine=google_scholar_author&hl=en', 'author_id': 'xKzbu4QAAAAJ'}, {'name': 'B Gu', 'link': 'https://scholar.google.com/citations?user=mR9b_ncAAAAJ&hl=en&num=20&oi=sra', 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=mR9b_ncAAAAJ&engine=google_scholar_author&hl=en', 'author_id': 'mR9b_ncAAAAJ'}, {'name': 'J Recker', 'link': 'https://scholar.google.com/citations?user=HQcik5oAAAAJ&hl=en&num=20&oi=sra', 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=HQcik5oAAAAJ&engine=google_scholar_author&hl=en', 'author_id': 'HQcik5oAAAAJ'}, {'name': 'R Santhanam', 'link': 'https://scholar.google.com/citations?user=O1oEZiEAAAAJ&hl=en&num=20&oi=sra', 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=O1oEZiEAAAAJ&engine=google_scholar_author&hl=en', 'author_id': 'O1oEZiEAAAAJ'}]}, 'resources': [{'title': 'academia.edu', 'file_format': 'PDF', 'link': 'https://www.academia.edu/download/75230000/Berente_Gu_Recker_Santhanam_2021_MISQ.pdf'}], 'inline_links': {'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&hl=en&q=75ZX7-22gRkJ', 'cited_by': {'total': 1019, 'link': 'https://scholar.google.com/scholar?cites=1837951255982872303&as_sdt=80005&sciodt=0,11&hl=en&num=20', 'cites_id': '1837951255982872303', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=80005&cites=1837951255982872303&engine=google_scholar&hl=en&num=20'}, 'related_pages_link': 'https://scholar.google.com/scholar?q=related:75ZX7-22gRkJ:scholar.google.com/&scioq=Artificial+Intelligence&hl=en&num=20&as_sdt=0,11&as_ylo=2019', 'serpapi_related_pages_link': 'https://serpapi.com/search.json?as_sdt=0%2C11&as_ylo=2019&engine=google_scholar&hl=en&num=20&q=related%3A75ZX7-22gRkJ%3Ascholar.google.com%2F', 'versions': {'total': 8, 'link': 'https://scholar.google.com/scholar?cluster=1837951255982872303&hl=en&num=20&as_sdt=0,11&as_ylo=2019', 'cluster_id': '1837951255982872303', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C11&as_ylo=2019&cluster=1837951255982872303&engine=google_scholar&hl=en&num=20'}, 'cached_page_link': 'https://scholar.googleusercontent.com/scholar?q=cache:75ZX7-22gRkJ:scholar.google.com/+Artificial+Intelligence&hl=en&num=20&as_sdt=0,11&as_ylo=2019'}}, {'position': 9, 'title': 'Fundamentals of artificial intelligence', 'result_id': '-6LWBK7RTN0J', 'type': 'Book', 'link': 'https://link.springer.com/content/pdf/10.1007/978-81-322-3972-7.pdf', 'snippet': '… some Institutions it is taught by the name Intelligent Systems. The concepts and theories of AI … scope of Artificial Intelligence as follows:1 Intelligent Systems (IS): Artificial intelligence (AI) …', 'publication_info': {'summary': 'KR Chowdhary - 2020 - Springer', 'authors': [{'name': 'KR Chowdhary', 'link': 'https://scholar.google.com/citations?user=ZFHvB4sAAAAJ&hl=en&num=20&oi=sra', 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=ZFHvB4sAAAAJ&engine=google_scholar_author&hl=en', 'author_id': 'ZFHvB4sAAAAJ'}]}, 'inline_links': {'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&hl=en&q=-6LWBK7RTN0J', 'cited_by': {'total': 408, 'link': 'https://scholar.google.com/scholar?cites=15946350925947773691&as_sdt=80005&sciodt=0,11&hl=en&num=20', 'cites_id': '15946350925947773691', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=80005&cites=15946350925947773691&engine=google_scholar&hl=en&num=20'}, 'related_pages_link': 'https://scholar.google.com/scholar?q=related:-6LWBK7RTN0J:scholar.g

/var/folders/82/kj1gp_ms0pjcvzrp5hvbtqg80000gn/T/ipykernel_76357/1602056600.py:17: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  if df.empty or not df['title'].str.contains(re['title']).any():

{'search_metadata': {'id': '67a898442bef571b7c0cf1be', 'status': 'Success', 'json_endpoint': 'https://serpapi.com/searches/ab633c39eb0b7142/67a898442bef571b7c0cf1be.json', 'created_at': '2025-02-09 11:57:56 UTC', 'processed_at': '2025-02-09 11:57:56 UTC', 'google_scholar_url': 'https://scholar.google.com/scholar?q=Machine+Learning&hl=en&num=21&as_ylo=2019', 'raw_html_file': 'https://serpapi.com/searches/ab633c39eb0b7142/67a898442bef571b7c0cf1be.html', 'total_time_taken': 1.48}, 'search_parameters': {'engine': 'google_scholar', 'q': 'Machine Learning', 'hl': 'en', 'num': '20', 'as_ylo': '2019'}, 'search_information': {'organic_results_state': 'Results for exact spelling', 'total_results': 1760000, 'time_taken_displayed': 0.09, 'query_displayed': 'Machine Learning'}, 'organic_results': [{'position': 1, 'title': 'Machine learning', 'result_id': 'EQ8shYj8Ai8J', 'type': 'Book', 'link': 'https://books.google.com/books?hl=en&lr=&id=ctM-EAAAQBAJ&oi=fnd&pg=PR6&dq=Machine+Learning&ots=o_LqT8Xw3u&sig=v_7oi_xL37Ajos6AByFw3lbGwkw', 'snippet': '… machine learning. The second part includes Chapters 4–10, which presents some classic and popular machine learning … cover the core topics of machine learning in one semester, and …', 'publication_info': {'summary': 'ZH Zhou - 2021 - books.google.com', 'authors': [{'name': 'ZH Zhou', 'link': 'https://scholar.google.com/citations?user=rSVIHasAAAAJ&hl=en&num=20&oi=sra', 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=rSVIHasAAAAJ&engine=google_scholar_author&hl=en', 'author_id': 'rSVIHasAAAAJ'}]}, 'inline_links': {'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&hl=en&q=EQ8shYj8Ai8J', 'cited_by': {'total': 2853, 'link': 'https://scholar.google.com/scholar?cites=3387547533016043281&as_sdt=5,44&sciodt=0,44&hl=en&num=20', 'cites_id': '3387547533016043281', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=5%2C44&cites=3387547533016043281&engine=google_scholar&hl=en&num=20'}, 'related_pages_link': 'https://scholar.google.com/scholar?q=related:EQ8shYj8Ai8J:scholar.google.com/&scioq=Machine+Learning&hl=en&num=20&as_sdt=0,44&as_ylo=2019', 'serpapi_related_pages_link': 'https://serpapi.com/search.json?as_sdt=0%2C44&as_ylo=2019&engine=google_scholar&hl=en&num=20&q=related%3AEQ8shYj8Ai8J%3Ascholar.google.com%2F', 'versions': {'total': 9, 'link': 'https://scholar.google.com/scholar?cluster=3387547533016043281&hl=en&num=20&as_sdt=0,44&as_ylo=2019', 'cluster_id': '3387547533016043281', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C44&as_ylo=2019&cluster=3387547533016043281&engine=google_scholar&hl=en&num=20'}}}, {'position': 2, 'title': 'Machine learning', 'result_id': '_zuqxloS2b0J', 'type': 'Book', 'link': 'https://books.google.com/books?hl=en&lr=&id=2nQJEAAAQBAJ&oi=fnd&pg=PR7&dq=Machine+Learning&ots=fI0bPa_Dou&sig=LOU1hZxNgcMN4OmS5UCalN8-Kn0', 'snippet': 'MIT presents a concise primer on machine learning—computer programs that learn from data and the basis of applications like voice recognition and driverless cars. No in-depth …', 'publication_info': {'summary': 'E Alpaydin - 2021 - books.google.com', 'authors': [{'name': 'E Alpaydin', 'link': 'https://scholar.google.com/citations?user=lXYKgiYAAAAJ&hl=en&num=20&oi=sra', 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=lXYKgiYAAAAJ&engine=google_scholar_author&hl=en', 'author_id': 'lXYKgiYAAAAJ'}]}, 'resources': [{'title': 'pomona.edu', 'file_format': 'PDF', 'link': 'https://cs.pomona.edu/~dkauchak/classes/s16/cs30-s16/lectures/lecture12-NN-basics.pdf'}], 'inline_links': {'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&hl=en&q=_zuqxloS2b0J', 'cited_by': {'total': 1234, 'link': 'https://scholar.google.com/scholar?cites=13679985524203994111&as_sdt=5,44&sciodt=0,44&hl=en&num=20', 'cites_id': '13679985524203994111', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=5%2C44&cites=13679985524203994111&engine=google_scholar&hl=en&num=20'}, 'related_pages_link': 'https://scholar.google.com/scholar?q=related:_zuqxloS2b0J:scholar.google.com/&scioq=Machine+Learning&hl=en&num=20&as_sdt=0,44&as_ylo=2019', 'serpapi_related_pages_link': 'https://serpapi.com/search.json?as_sdt=0%2C44&as_ylo=2019&engine=google_scholar&hl=en&num=20&q=related%3A_zuqxloS2b0J%3Ascholar.google.com%2F', 'versions': {'total': 11, 'link': 'https://scholar.google.com/scholar?cluster=13679985524203994111&hl=en&num=20&as_sdt=0,44&as_ylo=2019', 'cluster_id': '13679985524203994111', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C44&as_ylo=2019&cluster=13679985524203994111&engine=google_scholar&hl=en&num=20'}}}, {'position': 3, 'title': 'Machine learning algorithms-a review', 'result_id': 'sR_ChBn63tIJ', 'type': 'Pdf', 'link': 'https://www.researchgate.net/profile/Batta-Mahesh/publication/344717762_Machine_Learning_Algorithms_-A_Review/links/5f8b2365299bf1b53e2d243a/Machine-Learning-Algorithms-A-Review.pdf?eid=5082902844932096t', 'snippet': '… Here‟sa quick look at some of the commonly used algorithms in machine learning (ML) Supervised Learning Supervised learning is the machine learning task of learning a function …', 'publication_info': {'summary': 'B Mahesh - International Journal of Science and Research (IJSR) …, 2020 - researchgate.net'}, 'resources': [{'title': 'researchgate.net', 'file_format': 'PDF', 'link': 'https://www.researchgate.net/profile/Batta-Mahesh/publication/344717762_Machine_Learning_Algorithms_-A_Review/links/5f8b2365299bf1b53e2d243a/Machine-Learning-Algorithms-A-Review.pdf?eid=5082902844932096t'}], 'inline_links': {'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&hl=en&q=sR_ChBn63tIJ', 'cited_by': {'total': 3922, 'link': 'https://scholar.google.com/scholar?cites=15194857180303073201&as_sdt=5,44&sciodt=0,44&hl=en&num=20', 'cites_id': '15194857180303073201', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=5%2C44&cites=15194857180303073201&engine=google_scholar&hl=en&num=20'}, 'related_pages_link': 'https://scholar.google.com/scholar?q=related:sR_ChBn63tIJ:scholar.google.com/&scioq=Machine+Learning&hl=en&num=20&as_sdt=0,44&as_ylo=2019', 'serpapi_related_pages_link': 'https://serpapi.com/search.json?as_sdt=0%2C44&as_ylo=2019&engine=google_scholar&hl=en&num=20&q=related%3AsR_ChBn63tIJ%3Ascholar.google.com%2F', 'versions': {'total': 2, 'link': 'https://scholar.google.com/scholar?cluster=15194857180303073201&hl=en&num=20&as_sdt=0,44&as_ylo=2019', 'cluster_id': '15194857180303073201', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C44&as_ylo=2019&cluster=15194857180303073201&engine=google_scholar&hl=en&num=20'}, 'cached_page_link': 'https://scholar.googleusercontent.com/scholar?q=cache:sR_ChBn63tIJ:scholar.google.com/+Machine+Learning&hl=en&num=20&as_sdt=0,44&as_ylo=2019'}}, {'position': 4, 'title': 'Machine learning and law: An overview', 'result_id': 'nLsZrNC4QDEJ', 'link': 'https://www.elgaronline.com/abstract/edcoll/9781788972819/9781788972819.00014.xml', 'snippet': '… , machine learning has only recently started to develop. This chapter explores machine learning’s … The first section describes what machine learning is, highlighting its central principles. …', 'publication_info': {'summary': 'H Surden - Research Handbook on Big Data Law, 2021 - elgaronline.com', 'authors': [{'name': 'H Surden', 'link': 'https://scholar.google.com/citations?user=YBuBwXEAAAAJ&hl=en&num=20&oi=sra', 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=YBuBwXEAAAAJ&engine=google_scholar_author&hl=en', 'author_id': 'YBuBwXEAAAAJ'}]}, 'resources': [{'title': 'ssrn.com', 'file_format': 'PDF', 'link': 'https://papers.ssrn.com/sol3/Delivery.cfm?abstractid=2417415'}], 'inline_links': {'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&hl=en&q=nLsZrNC4QDEJ', 'cited_by': {'total': 938, 'link': 'https://scholar.google.com/scholar?cites=3549039712748026780&as_sdt=5,44&sciodt=0,44&hl=en&num=20', 'cites_id': '3549039712748026780', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=5%2C44&cites=3549039712748026780&engine=google_scholar&hl=en&num=20'}, 'related_pages_link': 'https://scholar.google.com/scholar?q=related:nLsZrNC4QDEJ:scholar.google.com/&scioq=Machine+Learning&hl=en&num=20&as_sdt=0,44&as_ylo=2019', 'serpapi_related_pages_link': 'https://serpapi.com/search.json?as_sdt=0%2C44&as_ylo=2019&engine=google_scholar&hl=en&num=20&q=related%3AnLsZrNC4QDEJ%3Ascholar.google.com%2F', 'versions': {'total': 11, 'link': 'https://scholar.google.com/scholar?cluster=3549039712748026780&hl=en&num=20&as_sdt=0,44&as_ylo=2019', 'cluster_id': '3549039712748026780', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C44&as_ylo=2019&cluster=3549039712748026780&engine=google_scholar&hl=en&num=20'}}}, {'position': 5, 'title': 'Machine learning and the physical sciences', 'result_id': 'eucrqVB_bisJ', 'link': 'https://journals.aps.org/rmp/abstract/10.1103/RevModPhys.91.045002', 'snippet': '… II, where the interaction with machine learning has a long history, drawing on methods in … in machine learning. We then turn the wheel in the other direction of using machine learning for …', 'publication_info': {'summary': 'G Carleo, I Cirac, K Cranmer, L Daudet, M Schuld… - Reviews of Modern …, 2019 - APS', 'authors': [{'name': 'G Carleo', 'link': 'https://scholar.google.com/citations?user=e9I38PEAAAAJ&hl=en&num=20&oi=sra', 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=e9I38PEAAAAJ&engine=google_scholar_author&hl=en', 'author_id': 'e9I38PEAAAAJ'}, {'name': 'I Cirac', 'link': 'https://scholar.google.com/citations?user=gPGlTbgAAAAJ&hl=en&num=20&oi=sra', 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=gPGlTbgAAAAJ&engine=google_scholar_author&hl=en', 'author_id': 'gPGlTbgAAAAJ'}, {'name': 'K Cranmer', 'link': 'https://scholar.google.com/citations?user=EZjSxgwAAAAJ&hl=en&num=20&oi=sra', 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=EZjSxgwAAAAJ&engine=google_scholar_author&hl=en', 'author_id': 'EZjSxgwAAAAJ'}, {'name': 'L Daudet', 'link': 'https://scholar.google.com/citations?user=PCIAcfUAAAAJ&hl=en&num=20&oi=sra', 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=PCIAcfUAAAAJ&engine=google_scholar_author&hl=en', 'author_id': 'PCIAcfUAAAAJ'}, {'name': 'M Schuld', 'link': 'https://scholar.google.com/citations?user=_ih_hwUAAAAJ&hl=en&num=20&oi=sra', 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=_ih_hwUAAAAJ&engine=google_scholar_author&hl=en', 'author_id': '_ih_hwUAAAAJ'}]}, 'resources': [{'title': 'aps.org', 'file_format': 'PDF', 'link': 'https://link.aps.org/accepted/10.1103/RevModPhys.91.045002'}], 'inline_links': {'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&hl=en&q=eucrqVB_bisJ', 'cited_by': {'total': 2521, 'link': 'https://scholar.google.com/scholar?cites=3129578775481411450&as_sdt=5,44&sciodt=0,44&hl=en&num=20', 'cites_id': '3129578775481411450', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=5%2C44&cites=3129578775481411450&engine=google_scholar&hl=en&num=20'}, 'related_pages_link': 'https://scholar.google.com/scholar?q=related:eucrqVB_bisJ:scholar.google.com/&scioq=Machine+Learning&hl=en&num=20&as_sdt=0,44&as_ylo=2019', 'serpapi_related_pages_link': 'https://serpapi.com/search.json?as_sdt=0%2C44&as_ylo=2019&engine=google_scholar&hl=en&num=20&q=related%3AeucrqVB_bisJ%3Ascholar.google.com%2F', 'versions': {'total': 14, 'link': 'https://scholar.google.com/scholar?cluster=3129578775481411450&hl=en&num=20&as_sdt=0,44&as_ylo=2019', 'cluster_id': '3129578775481411450', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C44&as_ylo=2019&cluster=3129578775481411450&engine=google_scholar&hl=en&num=20'}}}, {'position': 6, 'title': 'What is machine learning? A primer for the epidemiologist', 'result_id': 'LDE5SAcBB-gJ', 'link': 'https://academic.oup.com/aje/article-abstract/188/12/2222/5567515', 'snippet': '… We provide a brief introduction to 5 common machine learning … of machine learning techniques in the published literature. We recommend approaches to incorporate machine learning …', 'publication_info': {'summary': 'Q Bi, KE Goodman, J Kaminsky… - American journal of …, 2019 - academic.oup.com', 'authors': [{'name': 'Q Bi', 'link': 'https://scholar.google.com/citations?user=xzss3t0AAAAJ&hl=en&num=20&oi=sra', 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=xzss3t0AAAAJ&engine=google_scholar_author&hl=en', 'author_id': 'xzss3t0AAAAJ'}, {'name': 'J Kaminsky', 'link': 'https://scholar.google.com/citations?user=BFdcm_gAAAAJ&hl=en&num=20&oi=sra', 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=BFdcm_gAAAAJ&engine=google_scholar_author&hl=en', 'author_id': 'BFdcm_gAAAAJ'}]}, 'resources': [{'title': 'umsha.ac.ir', 'file_format': 'PDF', 'link': 'https://sph.umsha.ac.ir/uploads/18/2023/May/22/kwz189.pdf'}], 'inline_links': {'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&hl=en&q=LDE5SAcBB-gJ', 'cited_by': {'total': 672, 'link': 'https://scholar.google.com/scholar?cites=16719333272424362284&as_sdt=5,44&sciodt=0,44&hl=en&num=20', 'cites_id': '16719333272424362284', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=5%2C44&cites=16719333272424362284&engine=google_scholar&hl=en&num=20'}, 'related_pages_link': 'https://scholar.google.com/scholar?q=related:LDE5SAcBB-gJ:scholar.google.com/&scioq=Machine+Learning&hl=en&num=20&as_sdt=0,44&as_ylo=2019', 'serpapi_related_pages_link': 'https://serpapi.com/search.json?as_sdt=0%2C44&as_ylo=2019&engine=google_scholar&hl=en&num=20&q=related%3ALDE5SAcBB-gJ%3Ascholar.google.com%2F', 'versions': {'total': 9, 'link': 'https://scholar.google.com/scholar?cluster=16719333272424362284&hl=en&num=20&as_sdt=0,44&as_ylo=2019', 'cluster_id': '16719333272424362284', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C44&as_ylo=2019&cluster=16719333272424362284&engine=google_scholar&hl=en&num=20'}}}, {'position': 7, 'title': 'International conference on machine learning', 'result_id': 'gUoVCWuQbkcJ', 'type': 'Pdf', 'link': 'https://par.nsf.gov/servlets/purl/10418406', 'snippet': 'In this paper, we make the key delineation on the roles of resolution and statistical uncertainty in hierarchical bandits-based black-box optimization algorithms, guiding a more general …', 'publication_info': {'summary': 'W Li, C Wang, G Cheng, Q Song - Transactions on machine learning …, 2023 - par.nsf.gov', 'authors': [{'name': 'G Cheng', 'link': 'https://scholar.google.com/citations?user=KoXUMbsAAAAJ&hl=en&num=20&oi=sra', 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=KoXUMbsAAAAJ&engine=google_scholar_author&hl=en', 'author_id': 'KoXUMbsAAAAJ'}]}, 'resources': [{'title': 'nsf.gov', 'file_format': 'PDF', 'link': 'https://par.nsf.gov/servlets/purl/10418406'}], 'inline_links': {'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&hl=en&q=gUoVCWuQbkcJ', 'cited_by': {'total': 1743, 'link': 'https://scholar.google.com/scholar?cites=5147210213519346305&as_sdt=5,44&sciodt=0,44&hl=en&num=20', 'cites_id': '5147210213519346305', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=5%2C44&cites=5147210213519346305&engine=google_scholar&hl=en&num=20'}, 'related_pages_link': 'https://scholar.google.com/scholar?q=related:gUoVCWuQbkcJ:scholar.google.com/&scioq=Machine+Learning&hl=en&num=20&as_sdt=0,44&as_ylo=2019', 'serpapi_related_pages_link': 'https://serpapi.com/search.json?as_sdt=0%2C44&as_ylo=2019&engine=google_scholar&hl=en&num=20&q=related%3AgUoVCWuQbkcJ%3Ascholar.google.com%2F', 'cached_page_link': 'https://scholar.googleusercontent.com/scholar?q=cache:gUoVCWuQbkcJ:scholar.google.com/+Machine+Learning&hl=en&num=20&as_sdt=0,44&as_ylo=2019'}}, {'position': 8, 'title': 'The hundred-page machine learning book', 'result_id': 'JLoaFgwmnQcJ', 'type': 'Book', 'link': 'https://order-papers.com/sites/default/files/tmp/webform/order_download/pdf-the-hundred-page-machine-learning-book-andriy-burkov-pdf-download-free-book-d835289.pdf', 'snippet': "The book is divided into a three chapters and one that got the time. Because it dreamed of a dog i would be very proud to the actual story. When you get knowing you do n't listen to what …", 'publication_info': {'summary': 'A Burkov - 2019 - order-papers.com'}, 'resources': [{'title': 'order-papers.com', 'file_format': 'PDF', 'link': 'https://order-papers.com/sites/default/files/tmp/webform/order_download/pdf-the-hundred-page-machine-learning-book-andriy-burkov-pdf-download-free-book-d835289.pdf'}], 'inline_links': {'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&hl=en&q=JLoaFgwmnQcJ', 'cited_by': {'total': 1194, 'link': 'https://scholar.google.com/scholar?cites=548636562961381924&as_sdt=5,44&sciodt=0,44&hl=en&num=20', 'cites_id': '548636562961381924', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=5%2C44&cites=548636562961381924&engine=google_scholar&hl=en&num=20'}, 'related_pages_link': 'https://scholar.google.com/scholar?q=related:JLoaFgwmnQcJ:scholar.google.com/&scioq=Machine+Learning&hl=en&num=20&as_sdt=0,44&as_ylo=2019', 'serpapi_related_pages_link': 'https://serpapi.com/search.json?as_sdt=0%2C44&as_ylo=2019&engine=google_scholar&hl=en&num=20&q=related%3AJLoaFgwmnQcJ%3Ascholar.google.com%2F', 'versions': {'total': 3, 'link': 'https://scholar.google.com/scholar?cluster=548636562961381924&hl=en&num=20&as_sdt=0,44&as_ylo=2019', 'cluster_id': '548636562961381924', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C44&as_ylo=2019&cluster=548636562961381924&engine=google_scholar&hl=en&num=20'}, 'cached_page_link': 'https://scholar.googleusercontent.com/scholar?q=cache:JLoaFgwmnQcJ:scholar.google.com/+Machine+Learning&hl=en&num=20&as_sdt=0,44&as_ylo=2019'}}, {'position': 9, 'title': 'Amnesiac machine learning', 'result_id': '8JpyOA74dtgJ', 'link': 'https://ojs.aaai.org/index.php/AAAI/article/view/17371', 'snippet': '… It gives EU residents the ability to request deletion of their personal data, including training records used to train machine learning models. Unfortunately, Deep Neural Network models …', 'publication_info': {'summary': 'L Graves, V Nagisetty, V Ganesh - … of the AAAI Conference on Artificial …, 2021 - ojs.aaai.org', 'authors': [{'name': 'L Graves', 'link': 'https://scholar.google.com/citations?user=uTrKxm8AAAAJ&hl=en&num=20&oi=sra', 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=uTrKxm8AAAAJ&engine=google_scholar_author&hl=en', 'author_id': 'uTrKxm8AAAAJ'}, {'name': 'V Nagisetty', 'link': 'https://scholar.google.com/citations?user=9CaiG4UAAAAJ&hl=en&num=20&oi=sra', 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=9CaiG4UAAAAJ&engine=google_scholar_author&hl=en', 'author_id': '9CaiG4UAAAAJ'}, {'name': 'V Ganesh', 'link': 'https://scholar.google.com/citations?user=YP23eR0AAAAJ&hl=en&num=20&oi=sra', 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=YP23eR0AAAAJ&engine=google_scholar_author&hl=en', 'author_id': 'YP23eR0AAAAJ'}]}, 'resources': [{'title': 'aaai.org', 'file_format': 'PDF', 'link': 'https://ojs.aaai.org/index.php/AAAI/article/download/17371/17178'}], 'inline_links': {'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&hl=en&q=8JpyOA74dtgJ', 'cited_by': {'total': 264, 'link': 'https://scholar.google.com/scholar?cites=15597927099404557040&as_sdt=5,44&sciodt=0,44&hl=en&num=20', 'cites_id': '15597927099404557040', 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=5%2C44&cites=15597927099404557040&engine=google_scholar&hl=en&num=20'}, 'related_pages_link': 'https://scholar.google.com/scholar?q=related:8JpyOA74dtgJ:scholar.google.com/&scioq=Machine+Learning&hl=en&num=20&as_sdt=0,44&as_ylo=2019', 'serpapi_related_pages_li

In [208]:
#print(len(organic_results))
def extract_paper_info(organic_results, df):
    papers = []
    for re in organic_results:
        #print(re)
        if "resources" in re.keys(): 
            #print(re['resources'])
            for resource in re['resources']:
                if 'file_format' in resource.keys() and resource['file_format'] == 'PDF':
                    dict = {}
                    #print(resource['link'])
                    if "title" in re.keys():
                        dict['title'] = re['title']
                    if "snippet" in re.keys():
                        dict['snippet'] = re['snippet']
                    dict['link'] = resource['link']
                    if df.empty or not df['title'].str.contains(re['title']).any():
                        papers.append(dict)
                    elif df['title'].str.contains(re['title']).any(): print("중복 ", re['title'])
                else : print(resource)

    if papers:
        new_df = pd.DataFrame(papers)
        df = pd.concat([df, new_df], ignore_index=True)
    return df

In [8]:
df['title']

0               Applications for deep learning in ecology
1                      Machine learning and deep learning
2                           Fundamentals of deep learning
3                                    Deep learning for AI
4               The computational limits of deep learning
                              ...
2282    Revolutionizing healthcare: the role of artifi...
2283    AI-based smart prediction of clinical disease ...
2284    Challenges in establishing pure lung cancer or...
2285    “Bridging the Gap” Everything that Could Have ...
2286    Artificial intelligence (AI) in medicine, curr...
Name: title, Length: 2287, dtype: object

In [235]:
# DataFrame df를 'output.csv' 파일로 저장 (인덱스는 저장하지 않음)
df.to_csv('papers_link2.csv', index=False)

In [167]:
df['link'][19]

'https://aitskadapa.ac.in/e-books/AI&ML/DEEP%20LEARNING/MATLAB%20Deep%20Learning_%20With%20Machine%20Learning,%20Neural%20Networks%20and%20Artificial%20Intelligence%20(%20PDFDrive%20).pdf'

In [151]:
headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/115.0 Safari/537.36"
    )
}
response = requests.get(df['link'][17], headers=headers)
print(response)

<Response [200]>

In [2]:
def PDFtoTXT(url, output_filename, logger):
    try:
        response = requests.get(url)
        
        if response.status_code != 200:
            err_msg = f"HTTP 응답 코드 {response.status_code}"
            logger.debug(f"Error: {err_msg} - {output_filename}")
            return err_msg
        
        print("HTTP 응답 코드: 200 - PDF 파일 다운로드 성공")
        
        pdf_file = BytesIO(response.content)
    except: 
        err_msg = "request중 오류 발생"
        logger.debug(err_msg)
        return err_msg

    try:
        reader = PdfReader(pdf_file, strict=False)
    except Exception as e:
        err_msg = f"PDF 파일 읽기 오류: {str(e)}"
       #print(err_msg)
        logger.debug(err_msg)
        return err_msg

    full_text = ""
    for i, page in enumerate(reader.pages, start=1):
        text = page.extract_text()
        if text:
            full_text += f"==== Page {i} ====\n{text}\n\n"
        else:
            full_text += f"==== Page {i} ==== : 텍스트 추출 실패 또는 페이지가 비어 있음.\n\n"

    try:
        with open(output_filename, 'w', encoding='utf-8') as file:
            file.write(full_text)
        logger.debug(f"텍스트 추출 및 저장 완료: {output_filename}")
    except Exception as e:
        err_msg = f"파일 저장 오류: {str(e)}"
        logger.debug(err_msg)
        return err_msg
    
    return "success"

In [1]:
import requests
from io import BytesIO
from PyPDF2 import PdfReader
import pandas as pd

df = pd.read_csv('papers_link2.csv')
df

,title,snippet,link
0,Applications for deep learning in ecology,"… However, to our knowledge, we currently lack...",https://besjournals.onlinelibrary.wiley.com/do...
1,Machine learning and deep learning,… Machine learning describes the capacity of s...,https://link.springer.com/content/pdf/10.1007/...
2,Fundamentals of deep learning,"… , computer vision, and reinforcement learnin...",https://coursesteach.com/pluginfile.php/7459/m...
3,Deep learning for AI,… We reviewed the basic concepts and some of t...,https://dl.acm.org/doi/pdf/10.1145/3448250
4,The computational limits of deep learning,… deep learning is so computationally expensiv...,https://assets.pubpub.org/9c76pmmn/11686018723...
...,...,...,...
2282,Revolutionizing healthcare: the role of artifi...,… The advent of high-throughput genomic sequen...,https://link.springer.com/content/pdf/10.1186/...
2283,AI-based smart prediction of clinical disease ...,"… Thus, these data are only utilized for analy...",https://link.springer.com/content/pdf/10.1007/...
2284,Challenges in establishing pure lung cancer or...,… Clinical implementation of tumor organoids f...,https://www.cell.com/cell-reports/pdfExtended/...
2285,“Bridging the Gap” Everything that Could Have ...,… Gender medicine is the first step of persona...,https://www.mdpi.com/1422-0067/21/1/296/pdf
2286,"Artificial intelligence (AI) in medicine, curr...",… AI promises to revolutionize patient care in...,https://link.springer.com/content/pdf/10.1186/...

In [3]:
import os
from tqdm.auto import tqdm
import re

/Users/jejinan/Desktop/LLM_fine-tuning/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
import logging
import sys

# 로그 파일 이름과 포맷 설정
log_filename = 'output.log'
log_format = '%(asctime)s - %(levelname)s - %(message)s'

# 기본 로거 설정: FileHandler와 StreamHandler를 동시에 추가하여 파일과 콘솔에 로그를 출력
logging.basicConfig(
    level=logging.DEBUG,  # 필요한 로그 레벨 (DEBUG, INFO, WARNING, ERROR, CRITICAL)
    format=log_format,
    handlers=[
        logging.FileHandler(log_filename, encoding='utf-8'),  # 로그를 파일에 저장
        logging.StreamHandler(sys.stdout)  # 로그를 콘솔에 출력
    ]
)

logger = logging.getLogger()

In [ ]:
error_counts = {}
df_slice = df[2046:]
total = len(df_slice)


for i, row in tqdm(df_slice.iterrows(), total=total, desc="Processing PDFs", leave=True):
    link = row['link']
    title =  re.sub(r'[\\/*?:"<>|]', "", row['title'])
    
    output_filename = os.path.join("texts", f"{title}_{i}.txt")

    result = PDFtoTXT(link, output_filename, logger=logger)

    if result != "success":
        error_counts[result] = error_counts.get(result, 0) + 1

with open("error_counts.txt", "w", encoding="utf-8") as f:
    for err, count in error_counts.items():
        f.write(f"{err}: {count}\n")
# for i,link in enumerate(df['link']):  
#     PDFtoTXT(link, "texts/"+df.iloc[i]['title']+"_"+str(i)+".txt")

In [6]:
directory = "texts"
files = os.listdir(directory)

pattern = re.compile(r'_([0-9]{1,4})\.txt$')

max_number = -1
max_file = None

for file in files:
    match = pattern.search(file)
    if match:
        number = int(match.group(1))
        if number > max_number:
            max_number = number
            max_file = file

print("최대 숫자:", max_number)
print("해당 파일:", max_file)

최대 숫자: 2046
해당 파일: Neuroevolution of self-interpretable agents_2046.txt

In [120]:
import requests
from io import BytesIO
from pdfminer.high_level import extract_text

In [155]:

def pdfminerExtract(url, output_filename):
    """
    주어진 URL에서 PDF 파일을 다운로드한 후,
    pdfminer.six를 사용하여 텍스트를 추출하고,
    추출된 텍스트를 output_filename으로 저장합니다.
    """
    # 1. PDF 파일 다운로드
    headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0 Safari/537.36'
    }
    response = requests.get(url, headers=headers)
    if response.status_code != 200:
        print(f"Error: HTTP 응답 코드 {response.status_code}")
        return
    print("HTTP 응답 코드: 200 - PDF 파일 다운로드 성공")
    
    # 2. BytesIO 객체를 사용해 메모리 내에서 PDF 파일을 다룹니다.
    pdf_file = BytesIO(response.content)
    
    # 3. pdfminer.six의 extract_text 함수를 사용해 PDF 파일의 텍스트 추출
    try:
        text = extract_text(pdf_file)
    except Exception as e:
        print("텍스트 추출 중 오류 발생:", e)
        return
    
    # 4. 추출된 텍스트를 지정한 txt 파일로 저장
    try:
        with open(output_filename, 'w', encoding='utf-8') as f:
            f.write(text)
        print(f"텍스트 추출 및 저장 완료: {output_filename}")
    except Exception as e:
        print("파일 저장 중 오류 발생:", e)

# 함수 사용 예시
pdf_url = "https://necrocenenecrolandscaping.wordpress.com/wp-content/uploads/2018/01/braidotti_biopower-and-necropolitics.pdf"
output_file = "extracted_text_pdfminer.txt"
PDFtoTXT(pdf_url, output_file)

startxref on same line as offset

HTTP 응답 코드: 200 - PDF 파일 다운로드 성공
텍스트 추출 및 저장 완료: extracted_text_pdfminer.txt

In [ ]:
for i,link in enumerate(df['link']):  
    pdfminerExtract(link, "pdfminer"+str(i))

HTTP 응답 코드: 200 - PDF 파일 다운로드 성공
텍스트 추출 및 저장 완료: pdfminer0
HTTP 응답 코드: 200 - PDF 파일 다운로드 성공
텍스트 추출 및 저장 완료: pdfminer1
Error: HTTP 응답 코드 404
Error: HTTP 응답 코드 404
Error: HTTP 응답 코드 404
Error: HTTP 응답 코드 403
HTTP 응답 코드: 200 - PDF 파일 다운로드 성공
텍스트 추출 및 저장 완료: pdfminer6
HTTP 응답 코드: 200 - PDF 파일 다운로드 성공
텍스트 추출 및 저장 완료: pdfminer7
HTTP 응답 코드: 200 - PDF 파일 다운로드 성공
텍스트 추출 및 저장 완료: pdfminer8
HTTP 응답 코드: 200 - PDF 파일 다운로드 성공
텍스트 추출 및 저장 완료: pdfminer9
HTTP 응답 코드: 200 - PDF 파일 다운로드 성공
텍스트 추출 및 저장 완료: pdfminer10
HTTP 응답 코드: 200 - PDF 파일 다운로드 성공
텍스트 추출 및 저장 완료: pdfminer11
Error: HTTP 응답 코드 401
HTTP 응답 코드: 200 - PDF 파일 다운로드 성공
텍스트 추출 및 저장 완료: pdfminer13
HTTP 응답 코드: 200 - PDF 파일 다운로드 성공
텍스트 추출 및 저장 완료: pdfminer14
HTTP 응답 코드: 200 - PDF 파일 다운로드 성공
텍스트 추출 및 저장 완료: pdfminer15
HTTP 응답 코드: 200 - PDF 파일 다운로드 성공
텍스트 추출 및 저장 완료: pdfminer16
HTTP 응답 코드: 200 - PDF 파일 다운로드 성공
텍스트 추출 및 저장 완료: pdfminer17
HTTP 응답 코드: 200 - PDF 파일 다운로드 성공
텍스트 추출 및 저장 완료: pdfminer18
HTTP 응답 코드: 200 - PDF 파일 다운로드 성공
텍스트 추출 및 저장 완료: pdfminer19

In [139]:
import requests
from urllib.parse import urlparse, urlunparse

def bypass_403(url):
    # 기본 User-Agent 설정
    base_headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                      "AppleWebKit/537.36 (KHTML, like Gecko) "
                      "Chrome/115.0 Safari/537.36"
    }
    
    results = []  # 각 시도 결과를 저장

    # 1. IP/Host 스푸핑 헤더 추가
    spoof_headers = base_headers.copy()
    spoof_headers.update({
        "X-Forwarded-For": "127.0.0.1",
        "X-Forwarded-Host": "localhost",
        "X-Real-IP": "127.0.0.1",
        "Referer": "http://localhost"
    })
    print(">> 1. 스푸핑 헤더 사용")
    try:
        response = requests.get(url, headers=spoof_headers)
        results.append(("스푸핑 헤더", response.status_code, response.text))
    except Exception as e:
        print("스푸핑 헤더 요청 중 오류:", e)
    
    # 2. Path 기반 우회: URL 경로에 특수 문자를 삽입하여 우회
    parsed = urlparse(url)
    if parsed.path:
        # 예를 들어, /secret → /;%09/secret 형태로 변경
        new_path = "/;%09" + parsed.path
        new_url = urlunparse((parsed.scheme, parsed.netloc, new_path, 
                              parsed.params, parsed.query, parsed.fragment))
        print(">> 2. Path 기반 우회 시도:", new_url)
        try:
            response = requests.get(new_url, headers=base_headers)
            results.append(("Path 기반 우회", response.status_code, response.text))
        except Exception as e:
            print("Path 기반 우회 요청 중 오류:", e)
    
    # 3. HTTP 메소드 변경: GET 대신 POST 방식으로 요청
    print(">> 3. POST 메소드 사용")
    try:
        response = requests.post(url, headers=base_headers)
        results.append(("POST 메소드", response.status_code, response.text))
    except Exception as e:
        print("POST 메소드 요청 중 오류:", e)
    
    # 4. URL 재작성 헤더 사용
    rewrite_headers = base_headers.copy()
    rewrite_headers.update({"X-Rewrite-URL": url})
    print(">> 4. X-Rewrite-URL 헤더 사용")
    try:
        response = requests.get(url, headers=rewrite_headers)
        results.append(("X-Rewrite-URL 헤더", response.status_code, response.text))
    except Exception as e:
        print("X-Rewrite-URL 헤더 요청 중 오류:", e)
    
    # 결과 출력: 각 방식별 상태 코드와 일부 응답 내용을 확인
    print("\n=== 우회 시도 결과 ===")
    for method, code, text in results:
        print(f"[{method}] 응답 코드: {code}")
        # 응답 내용의 앞 200자를 출력합니다.
        print(text[:200])
        print("-" * 50)
    
    return results

In [8]:
df['link'][63]

'https://www.frontiersin.org/journals/plant-science/articles/10.3389/fpls.2019.01750/pdf'

In [ ]:
bypass_403(df['link'][3])

>> 1. 스푸핑 헤더 사용
>> 2. Path 기반 우회 시도: https://citeseerx.ist.psu.edu/;%09/document?repid=rep1&type=pdf&doi=573027eaaf46bd4181b1864fe6088a7a7a90d912
>> 3. POST 메소드 사용
>> 4. X-Rewrite-URL 헤더 사용

=== 우회 시도 결과 ===
[스푸핑 헤더] 응답 코드: 200
%PDF-1.2
%����
1 0 obj
<</Title (Bio-photons and Bio-communication)
/Creator (RealPage PDF Generator 1.0)
/Author ()
/CreationDate (D:20020306000407)
/Producer (RealPage data converter)
>>
endobj
5 0
--------------------------------------------------
[Path 기반 우회] 응답 코드: 404
<!doctype html>
<html data-n-head-ssr lang="en" data-n-head="%7B%22lang%22:%7B%22ssr%22:%22en%22%7D%7D">
  <head >
    <title>This page could not be found</title><meta data-n-head="ssr" charset="utf-8
--------------------------------------------------
[POST 메소드] 응답 코드: 405
{"detail":"Method Not Allowed"}
--------------------------------------------------
[X-Rewrite-URL 헤더] 응답 코드: 200
%PDF-1.2
%����
1 0 obj
<</Title (Bio-photons and Bio-communication)
/Creator (RealPage PDF Generator 1.0)
/Author ()
/CreationDate (D:20020306000407)
/Producer (RealPage data converter)
>>
endobj
5 0
--------------------------------------------------

[('스푸핑 헤더',
  200,